import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The site runs under COEP `require-corp`, so a Google Fonts `<link>` is not just a
 * privacy problem — it is a blocked request. Fonts have to be files.
 *
 * `@fontsource/*` ships exactly that, but its CSS is scoped to one family per package and
 * names its files after the subset. This copies the faces we use into `public/fonts/` with
 * stable, readable names and regenerates `src/fonts.css` to match, so the `@font-face`
 * rules can never drift from the bytes on disk. To change a weight or add a family, edit
 * `FACES` and re-run; `tailwind.config.js` still has to name the family in `fontFamily`.
 *
 * Dev-time only: nothing here reaches the browser as a dependency.
 */
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "public/fonts");
mkdirSync(out, { recursive: true });

const FACES = [
  { pkg: "@fontsource/instrument-serif", css: "latin-400.css", as: "instrument-serif-400.woff2" },
  { pkg: "@fontsource/instrument-serif", css: "latin-400-italic.css", as: "instrument-serif-400-italic.woff2" },
  { pkg: "@fontsource/spline-sans", css: "latin-400.css", as: "spline-sans-400.woff2" },
  { pkg: "@fontsource/spline-sans", css: "latin-500.css", as: "spline-sans-500.woff2" },
  { pkg: "@fontsource/spline-sans", css: "latin-600.css", as: "spline-sans-600.woff2" },
  { pkg: "@fontsource/spline-sans-mono", css: "latin-400.css", as: "spline-sans-mono-400.woff2" },
  { pkg: "@fontsource/spline-sans-mono", css: "latin-500.css", as: "spline-sans-mono-500.woff2" },
];

const rules = [];
const seenPkgs = new Set();
const unquote = (value) => value.trim().replace(/^['"]|['"]$/g, "");

for (const face of FACES) {
  const cssPath = resolve(root, "node_modules", face.pkg, face.css);
  const css = readFileSync(cssPath, "utf8");

  const urls = [...css.matchAll(/url\(([^)]+\.woff2)\)/g)].map((m) => m[1]);
  if (urls.length !== 1) {
    throw new Error(`vendor-fonts: expected one woff2 in ${cssPath}, found ${urls.length}`);
  }

  copyFileSync(resolve(dirname(cssPath), urls[0]), resolve(out, face.as));

  const family = /font-family:\s*([^;,]+)/.exec(css);
  const weight = /font-weight:\s*([^;,]+)/.exec(css);
  const style = /font-style:\s*([^;,]+)/.exec(css);
  if (!family || !weight || !style) {
    throw new Error(`vendor-fonts: could not read family/weight/style out of ${cssPath}`);
  }


  rules.push(
    [
      "@font-face {",
      `  font-family: "${unquote(family[1])}";`,
      `  font-style: ${unquote(style[1])};`,
      `  font-weight: ${unquote(weight[1])};`,
      "  font-display: swap;",
      `  src: url('/fonts/${face.as}') format('woff2');`,
      "}",
    ].join("\n")
  );

  if (!seenPkgs.has(face.pkg)) {
    seenPkgs.add(face.pkg);
    const licence = resolve(root, "node_modules", face.pkg, "LICENSE");
    copyFileSync(licence, resolve(out, `${face.pkg.replace("@fontsource/", "")}-LICENSE.txt`));
  }
  process.stdout.write(`  ${face.as}\n`);
}

writeFileSync(
  resolve(root, "src/fonts.css"),
  `/* Generated by scripts/vendor-fonts.mjs — do not edit; run \`npm run fonts\`. */\n${rules.join("\n")}\n`
);

console.log(`vendored ${FACES.length} faces -> public/fonts/ and src/fonts.css`);
